name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install main dependencies
        run: npm install
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Check style
        run: npm run lint
      - name: build
        run: npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_prefix: ""
          release_type: "patch"
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}

  deploy:
    needs: [tag_release]
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '#skip') }}
      - name: Test Success
        uses: tsickert/discord-webhook@v6.0.0
        if: success() && github.ref == 'refs/heads/main'
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "A new version of PhoneBookApp deployed"
          username: "Deployment Bot"
          embed-title: "Deployment Success"
          embed-description: "A new version of PhoneBookApp has been successfully deployed."
      - name: Test Failure
        uses: tsickert/discord-webhook@v6.0.0
        if: failure() && github.ref == 'refs/heads/main'
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Build Failure Detected"
          username: "Deployment Bot"
          embed-title: "Deployment Failure"
          embed-description: "Commit by ${{ github.actor }} broke the build."